######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 21:02:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mainview.h choicesview.h
SOURCES += main.cpp mainwindow.cpp mainview.cpp choicesview.cpp
